#!/usr/bin/env python3
"""Build a single-file copy of the site with the images inlined as data URIs.

index.html is the version to host (GitHub Pages, or anywhere that can serve the
assets/ folder next to it). Some hosts — the GoDaddy site editor among them —
only take one pasted HTML file and give you nowhere to put assets/. This writes
GrigoriNightDragon-site.html, which is byte-identical in behaviour but carries
its own artwork, so it renders correctly with no upload step.

Usage: python3 tools/build_standalone.py
"""

import base64
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "index.html"
OUT = ROOT / "GrigoriNightDragon-site.html"

MIME = {".webp": "image/webp", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".png": "image/png"}


def data_uri(rel):
    path = ROOT / rel
    mime = MIME.get(path.suffix.lower())
    if mime is None:
        raise SystemExit(f"unknown asset type: {rel}")
    return "data:" + mime + ";base64," + base64.b64encode(path.read_bytes()).decode("ascii")


def main():
    if not SRC.exists():
        raise SystemExit(f"missing {SRC}")

    html = SRC.read_text(encoding="utf-8")

    # Inlining both the WebP and its JPEG fallback would carry the same artwork
    # twice, at ~4/3 size once base64'd. Every browser that runs this page reads
    # WebP, so collapse the <picture> to the WebP alone and drop the fallback.
    html = re.sub(r'\s*<source srcset="assets/gnd-key-art\.webp"[^>]*>', "", html)
    html = html.replace('src="assets/gnd-key-art.jpg"', 'src="assets/gnd-key-art.webp"')

    # Every local asset reference, wherever it appears (src, srcset, href).
    refs = sorted(set(re.findall(r'(?:src|srcset|href)="(assets/[^"]+)"', html)))
    if not refs:
        raise SystemExit("no assets/ references found — has index.html changed?")

    for rel in refs:
        html = html.replace('"' + rel + '"', '"' + data_uri(rel) + '"')

    # The canonical/og URLs point at the hosted copy; a pasted single file is a
    # different page at a different address, so drop the tags rather than have
    # them claim to be the GitHub Pages original.
    html = re.sub(r'\n\s*<link rel="canonical"[^>]*>', "", html)
    html = re.sub(r'\n\s*<meta property="og:image"[^>]*>', "", html)

    html = html.replace(
        "<title>",
        "<!-- Generated by tools/build_standalone.py from index.html — edit that, not this. -->\n<title>",
        1,
    )

    OUT.write_text(html, encoding="utf-8")

    leftover = re.findall(r'(?:src|srcset|href)="(assets/[^"]+)"', html)
    if leftover:
        raise SystemExit(f"FAIL still references local assets: {leftover}")

    print(f"wrote {OUT.name}  ({OUT.stat().st_size/1024:.0f} KB, {len(refs)} assets inlined)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
